//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterResourceOverride) DeepCopyInto(out *ClusterResourceOverride) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterResourceOverride.
func (in *ClusterResourceOverride) DeepCopy() *ClusterResourceOverride {
	if in == nil {
		return nil
	}
	out := new(ClusterResourceOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterResourceOverride) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterResourceOverrideCondition) DeepCopyInto(out *ClusterResourceOverrideCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterResourceOverrideCondition.
func (in *ClusterResourceOverrideCondition) DeepCopy() *ClusterResourceOverrideCondition {
	if in == nil {
		return nil
	}
	out := new(ClusterResourceOverrideCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterResourceOverrideList) DeepCopyInto(out *ClusterResourceOverrideList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterResourceOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterResourceOverrideList.
func (in *ClusterResourceOverrideList) DeepCopy() *ClusterResourceOverrideList {
	if in == nil {
		return nil
	}
	out := new(ClusterResourceOverrideList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterResourceOverrideList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterResourceOverrideResourceHash) DeepCopyInto(out *ClusterResourceOverrideResourceHash) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterResourceOverrideResourceHash.
func (in *ClusterResourceOverrideResourceHash) DeepCopy() *ClusterResourceOverrideResourceHash {
	if in == nil {
		return nil
	}
	out := new(ClusterResourceOverrideResourceHash)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterResourceOverrideResources) DeepCopyInto(out *ClusterResourceOverrideResources) {
	*out = *in
	if in.ConfigurationRef != nil {
		in, out := &in.ConfigurationRef, &out.ConfigurationRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.ServiceCAConfigMapRef != nil {
		in, out := &in.ServiceCAConfigMapRef, &out.ServiceCAConfigMapRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.ServiceRef != nil {
		in, out := &in.ServiceRef, &out.ServiceRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.ServiceCertSecretRef != nil {
		in, out := &in.ServiceCertSecretRef, &out.ServiceCertSecretRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.DeploymentRef != nil {
		in, out := &in.DeploymentRef, &out.DeploymentRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.APiServiceRef != nil {
		in, out := &in.APiServiceRef, &out.APiServiceRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.MutatingWebhookConfigurationRef != nil {
		in, out := &in.MutatingWebhookConfigurationRef, &out.MutatingWebhookConfigurationRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterResourceOverrideResources.
func (in *ClusterResourceOverrideResources) DeepCopy() *ClusterResourceOverrideResources {
	if in == nil {
		return nil
	}
	out := new(ClusterResourceOverrideResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterResourceOverrideSpec) DeepCopyInto(out *ClusterResourceOverrideSpec) {
	*out = *in
	out.PodResourceOverride = in.PodResourceOverride
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterResourceOverrideSpec.
func (in *ClusterResourceOverrideSpec) DeepCopy() *ClusterResourceOverrideSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterResourceOverrideSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterResourceOverrideStatus) DeepCopyInto(out *ClusterResourceOverrideStatus) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	out.Hash = in.Hash
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ClusterResourceOverrideCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.CertsRotateAt.DeepCopyInto(&out.CertsRotateAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterResourceOverrideStatus.
func (in *ClusterResourceOverrideStatus) DeepCopy() *ClusterResourceOverrideStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterResourceOverrideStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodResourceOverride) DeepCopyInto(out *PodResourceOverride) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodResourceOverride.
func (in *PodResourceOverride) DeepCopy() *PodResourceOverride {
	if in == nil {
		return nil
	}
	out := new(PodResourceOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodResourceOverrideSpec) DeepCopyInto(out *PodResourceOverrideSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodResourceOverrideSpec.
func (in *PodResourceOverrideSpec) DeepCopy() *PodResourceOverrideSpec {
	if in == nil {
		return nil
	}
	out := new(PodResourceOverrideSpec)
	in.DeepCopyInto(out)
	return out
}
