//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelinuxFixOverride) DeepCopyInto(out *SelinuxFixOverride) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelinuxFixOverride.
func (in *SelinuxFixOverride) DeepCopy() *SelinuxFixOverride {
	if in == nil {
		return nil
	}
	out := new(SelinuxFixOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SelinuxFixOverride) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelinuxFixOverrideCondition) DeepCopyInto(out *SelinuxFixOverrideCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelinuxFixOverrideCondition.
func (in *SelinuxFixOverrideCondition) DeepCopy() *SelinuxFixOverrideCondition {
	if in == nil {
		return nil
	}
	out := new(SelinuxFixOverrideCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelinuxFixOverrideList) DeepCopyInto(out *SelinuxFixOverrideList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SelinuxFixOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelinuxFixOverrideList.
func (in *SelinuxFixOverrideList) DeepCopy() *SelinuxFixOverrideList {
	if in == nil {
		return nil
	}
	out := new(SelinuxFixOverrideList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SelinuxFixOverrideList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelinuxFixOverrideResourceHash) DeepCopyInto(out *SelinuxFixOverrideResourceHash) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelinuxFixOverrideResourceHash.
func (in *SelinuxFixOverrideResourceHash) DeepCopy() *SelinuxFixOverrideResourceHash {
	if in == nil {
		return nil
	}
	out := new(SelinuxFixOverrideResourceHash)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelinuxFixOverrideSpec) DeepCopyInto(out *SelinuxFixOverrideSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelinuxFixOverrideSpec.
func (in *SelinuxFixOverrideSpec) DeepCopy() *SelinuxFixOverrideSpec {
	if in == nil {
		return nil
	}
	out := new(SelinuxFixOverrideSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelinuxFixOverrideStatus) DeepCopyInto(out *SelinuxFixOverrideStatus) {
	*out = *in
	out.Hash = in.Hash
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]SelinuxFixOverrideCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.CertsRotateAt.DeepCopyInto(&out.CertsRotateAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelinuxFixOverrideStatus.
func (in *SelinuxFixOverrideStatus) DeepCopy() *SelinuxFixOverrideStatus {
	if in == nil {
		return nil
	}
	out := new(SelinuxFixOverrideStatus)
	in.DeepCopyInto(out)
	return out
}
